/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "JodexIndustries Wiki",
  "tagline": "Ukrainian development studio for Minecraft",
  "favicon": "img/favicon.ico",
  "url": "https://wiki.jodexindustries.xyz",
  "baseUrl": "/ru/",
  "organizationName": "Jodexx",
  "projectName": "JodexIndustriesWiki",
  "trailingSlash": false,
  "onBrokenLinks": "ignore",
  "onBrokenMarkdownLinks": "ignore",
  "i18n": {
    "defaultLocale": "ua",
    "locales": [
      "ua",
      "en",
      "ru"
    ],
    "path": "i18n",
    "localeConfigs": {
      "en": {
        "htmlLang": "en-US",
        "direction": "ltr"
      },
      "ru": {
        "htmlLang": "ru-RU",
        "direction": "ltr"
      },
      "ua": {
        "label": "Українська",
        "htmlLang": "ua-UA",
        "direction": "ltr"
      }
    }
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "D:\\JodexIndustries\\JodexIndustriesWiki\\sidebars.js",
          "lastVersion": "current",
          "versions": {
            "current": {
              "label": "2.0.0",
              "path": "2.0.0"
            }
          }
        },
        "theme": {
          "customCss": "D:\\JodexIndustries\\JodexIndustriesWiki\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/logo.png",
    "navbar": {
      "title": "JodexIndustries Wiki",
      "logo": {
        "alt": "JodexIndustries Logo",
        "src": "img/logo.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "defaultSidebar",
          "position": "left",
          "label": "Документация"
        },
        {
          "type": "localeDropdown",
          "position": "left",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "type": "docsVersionDropdown",
          "position": "left",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Документация",
          "items": [
            {
              "label": "DonateCase",
              "to": "/docs/donatecase"
            }
          ]
        },
        {
          "title": "Сообщество",
          "items": [
            {
              "label": "Веб-сайт",
              "href": "https://www.jodexindustries.xyz"
            },
            {
              "label": "Discord",
              "href": "https://discord.gg/8XT8zJb5"
            }
          ]
        },
        {
          "title": "Ещё",
          "items": [
            {
              "label": "Jodexx GitHub",
              "href": "https://github.com/Jodexx"
            },
            {
              "label": "JodexIndustries GitHub",
              "href": "https://github.com/JodexIndustries"
            }
          ]
        }
      ],
      "copyright": "Авторские права © 2024 JodexIndustries"
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "java",
        "gradle",
        "yaml",
        "xml-doc"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "future": {
    "experimental_faster": {
      "swcJsLoader": true,
      "swcJsMinimizer": true,
      "swcHtmlMinimizer": true,
      "lightningCssMinimizer": true,
      "rspackBundler": true,
      "mdxCrossCompilerCache": true
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
